import{a as C,i as n,S as T}from"./assets/vendor-cec502ba.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))a(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const f of r.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&a(f)}).observe(document,{childList:!0,subtree:!0});function s(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(o){if(o.ep)return;o.ep=!0;const r=s(o);fetch(o.href,r)}})();const M="43082908-d5bb253eb19cb17ad501330a7",S="https://pixabay.com/api/";async function g(t,e,s){try{return(await C.get(S,{params:{key:M,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:s}})).data}catch(a){throw n.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topCenter"}),a}}const l=document.querySelector(".gallery"),L=new T(".gallery a",{captionsData:"alt",captionDelay:250});L.refresh();function E(t){t.forEach(e=>{const s=`
            <li class="card">
                <a href="${e.largeImageURL}" class="link">
                    <img src="${e.webformatURL}" alt="${e.tags}">
                    <ul class="list-container">
                        <li class="item-description"><h3>Likes</h3> <p>${e.likes}</p></li>
                        <li class="item-description"><h3>Views</h3> <p>${e.views}</p></li>
                        <li class="item-description"><h3>Comments</h3> <p>${e.comments}</p></li>
                        <li class="item-description"><h3>Downloads</h3> <p>${e.downloads}</p></li>
                    </ul>
                </a>
            </li>
        `;l.insertAdjacentHTML("beforeend",s)}),L.refresh()}function b(){const t=document.createElement("p");t.classList.add("end-message"),t.textContent="We're sorry, but you've reached the end of search results.",n.info({title:"Info",message:t.textContent,position:"topCenter"}),l.insertAdjacentElement("afterend",t)}const p=document.querySelector(".scroll-to-top"),q=document.querySelector(".form"),y=document.querySelector(".search-input"),w=document.querySelector(".loader"),u=document.querySelector(".load-more-btn");h();let c="",i=1;const m=15;q.addEventListener("submit",H);async function H(t){if(t.preventDefault(),c=y.value.trim(),i=1,l.innerHTML="",c===""){n.error({title:"Error",message:"Please enter a search term.",position:"topCenter"}),d();return}O(),v();try{const e=await g(c,i,m),s=e.totalHits;if(e.hits.length===0){l.innerHTML="",n.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topCenter"}),d();return}else E(e.hits),y.value="",P();m*i>=s&&(d(),b())}catch(e){console.error("Error fetching images:",e),n.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topCenter"})}finally{h()}}u.addEventListener("click",async()=>{try{u&&(i+=1);const t=await g(c,i,m),e=t.totalHits;E(t.hits),v(),m*i>=e&&(d(),b());const s=l.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:s*3,behavior:"smooth"})}catch(t){console.error("Error fetching more images:",t),n.error({title:"Error",message:`Error fetching more images: ${t}`})}finally{h()}});function v(){w.classList.remove("hidden")}function h(){w.classList.add("hidden")}function P(){u.style.display="block"}function d(){u.style.display="none"}function O(){const t=document.querySelector(".end-message");t&&t.remove()}window.addEventListener("scroll",()=>{document.body.scrollTop>30||document.documentElement.scrollTop>30?p.style.display="flex":p.style.display="none"});function $(){window.scrollTo({top:0,behavior:"smooth"})}p.addEventListener("click",$);
//# sourceMappingURL=commonHelpers.js.map
